### PR TITLE
RHIDP-3430: fix(checkbox): update selected bg color

### PR DESCRIPTION
**Pull request by ciiay**
For [RHIDP-3430](https://issues.redhat.com/browse/RHIDP-3430)

Screen recording

https://github.com/user-attachments/assets/c27f1510-8f1f-447f-ab59-24ed09438d83

### CODE REVIEW

**Comment by ShiranHi** [comment]
Looks good, thank you @ciiay

**Comment by jerolimov** [comment]
Hhmmm, I think we should change the secondary color instead. Is that an option that we change all checkboxes to that blue? I remember I discussed this with @ShiranHi somewhere but didn't followup on that.

**Comment by ciiay** [comment]
Hi @jerolimov , do you mean we make the secondary color same as primary color? Then there won't be a secondary color available for users. Shouldn't we leave that option to users?

**Comment by ShiranHi** [comment]
I'm not quite sure why we need a secondary color, but as long as the color we use follows the [PF guidelines](https://www.patternfly.org/components/menus/select/html-deprecated/#checkbox), I'm fine with it. I noticed that the primary Blue color in dark mode is a bit brighter - let's make sure we're sticking to that:
image

**Comment by ciiay** [comment]
Cool, thanks for the reply @ShiranHi . In this case, @jerolimov I can update the secondary color same as primary then, might be a good idea if we don't need a set of secondary color at all.

**Comment by jerolimov** [comment]
> Hi @jerolimov , do you mean we make the secondary color same as primary color? Then there won't be a secondary color available for users. Shouldn't we leave that option to users?

Yeah I guess we can just change the color (as you have done), and keep the option for customers to change it into 2 colors if they prefer two different colors.

**Review by jerolimov — APPROVED** [review]
Diff looks good, but I would like to test it a bit before I push the merge button.

/lgtm
/approve

**Comment by jerolimov** [comment]
I guess the change to primary=secondary color is okayish as PF has no secondary color.

But I like to double-check with you both, that this will affect more than just the checkboxes in the catalog. As an example, it also affects the catalog graph (and all secondary buttons of course):

| Before | With this PR |
| --- | --- |
| image | image |
| image | image |
| image | image |
| image | image |

Here is how the backstage filter is implemented:

https://github.com/backstage/backstage/blob/27b099cbe24d3fcdaa9b032c335fa83f4b9cd6f2/plugins/catalog-react/src/components/EntityOwnerPicker/EntityOwnerPicker.tsx#L89-L103

It still uses the Material UI v4 Checkbox component: https://v4.mui.com/components/checkboxes/#checkbox

/cc @ShiranHi @ciiay

**Review by jerolimov — APPROVED** [review]
/lgtm

**Comment by jerolimov** [comment]
As discussed today with @ShiranHi we want switch all buttons, tabs, etc. to blue. Customers might change this back to two different colors, but for now, we want to continue with a version that never has purple buttons. ;)

**Pull request merged**
